USE `if0_39852454_conafe_db`;

ALTER TABLE `EXAMENES`
ADD COLUMN `TipoExamen` VARCHAR(50) NOT NULL DEFAULT 'Parcial',
ADD COLUMN `Duracion` INT NOT NULL DEFAULT 0,
ADD COLUMN `Observaciones` TEXT NULL;
